In [35]:
import numpy as np
import torch as tc
import os

In [58]:
dictionary = {'geek': 1, 'supergeek': True, 4: 'geeky'} 

try: 
    geeky_file = open('geekyfile.txt', 'at') 
    geeky_file.write("\n") 
    geeky_file.write(str(dictionary)) 
    geeky_file.close() 

except: 
    print("Unable to write to file")


In [71]:
recon_path = 'data/sample3_recon'
f_recon_parameters = 'recon_parameters.txt'

# with open(os.path.join(recon_path, f_recon_parameters), "r") as f:
#      dog_list = f.readlines()
# print(dog_list)   

dog_list = []
print("\n")
with open(os.path.join(recon_path, f_recon_parameters), "a") as f:
    f.write("afhsdfiah\n")

# last_epoch = int(dog_list[1][dog_list[1].find("=")+1:])
# print(last_epoch)

In [4]:
dic = {}

In [5]:
dic["name"] = "Mary"

In [73]:
a = tc.ones(10,5)

b = 2 * tc.ones(1,5)

c = tc.cat((a,b))
print(c.shape)

torch.Size([11, 5])


In [92]:
b1 = np.array([1])
b1 = b1.tolist()

b2 = np.array([2,3])
b2 = b2.tolist()

print(b1)
print(a)

[1]
[]


In [93]:
a.append(b1)
a.append(b2)
print(a)

[[1], [2, 3]]


In [94]:
a.append(b2)
print(a)

[[1], [2, 3], [2, 3]]


In [95]:
a1 = np.array(a)
print(a1)

[list([1]) list([2, 3]) list([2, 3])]


In [96]:
a2 = np.asarray(a)
print(a2)

[list([1]) list([2, 3]) list([2, 3])]


In [38]:
print(a)
a3 = tc.tensor(a)
print(a3)

NameError: name 'a' is not defined

In [51]:
a =  tc.ones(7)
b = 2 * tc.ones(7)
b = tc.cat((b, b[0].view(1)))
print(a)
print(b)

tensor([1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2., 2., 2., 2.])


In [104]:
ab = tc.stack([a,b])
print(ab)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2.]])


In [105]:
ab = tc.stack([a,b], dim=1)
print(ab)

tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])
