In [81]:
import numpy as np
import torch as tc

In [2]:
dic = {}

In [4]:
dic["name"] = "Mary"

In [91]:
a = []

In [92]:
b1 = np.array([1])
b1 = b1.tolist()

b2 = np.array([2,3])
b2 = b2.tolist()

print(b1)
print(a)

[1]
[]


In [93]:
a.append(b1)
a.append(b2)
print(a)

[[1], [2, 3]]


In [94]:
a.append(b2)
print(a)

[[1], [2, 3], [2, 3]]


In [95]:
a1 = np.array(a)
print(a1)

[list([1]) list([2, 3]) list([2, 3])]


In [96]:
a2 = np.asarray(a)
print(a2)

[list([1]) list([2, 3]) list([2, 3])]


In [97]:
print(a)
a3 = tc.tensor(a)
print(a3)

[[1], [2, 3], [2, 3]]


ValueError: expected sequence of length 1 at dim 1 (got 2)

In [102]:
a =  tc.ones(7)
b = 2 * tc.ones(7)
print(a)
print(b)

tensor([1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2., 2., 2.])


In [104]:
ab = tc.stack([a,b])
print(ab)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2.]])


In [105]:
ab = tc.stack([a,b], dim=1)
print(ab)

tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])
