In [2]:
import numpy as np
import torch as tc

In [18]:
a1 = np.ones((3,3,3,1))
a2 = 2 * np.ones((3,3,3,1))

ad = np.dstack((a1, a2))
print(ad.shape)

(3, 3, 6, 1)


In [19]:
a1 = np.array([1,2,3])
a2 = np.array([1,2,3])

In [20]:
a3 = (a1 == a2).all()
print(a3)

True


In [16]:
a = np.clip(a1, 0,2)
print(a)

[1 2 2]


In [7]:
a = np.array([[1,2,3], [3,4,5]])
b = np.stack((np.array([]), np.array([]), np.array([])), axis=-1)
c = np.concatenate((a,b))
print(a.shape)
print(b.shape)
print(c)

(2, 3)
(0, 3)
[[1. 2. 3.]
 [3. 4. 5.]]


In [38]:
#Demonstration of output formats for strings, floats, and integers

name = "Norm"
mark1 = 86
mark2 = 77.6154617



#note:  the float is rounded up where necessary
#note:  to get a percent sign printed, you must use two %% together
print("%1s got %1.9f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1.8f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1.7f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1.6f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1.5f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1.4f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1.3f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1.2f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1.1f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1.0f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1.f%% on the test number %1d." % (name,mark2,mark1))
print("%1s got %1f%% on the test number %1d." % (name,mark2,mark1))

print("\n")

#note:  for unknown length, use either a '0' or 'nothing'
print("%0s got %0.2f%% on the test number %0d." % (name,mark2,mark1))
print("%s got %.2f%% on the test number %d." % (name,mark2,mark1))
print("%s got %f%% on the test number %d." % (name,mark2,mark1))

print

#note:  if the field is larger than the value, it is right adjusted.
print ("%8s got %8.2f%% on the test number %8d." % (name,mark2,mark1))
#note:  the negative number left adjusts.
print ("%-8s got %-8.2f%% on the test number %-8d." % (name,mark2,mark1))

Norm got 77.615461700% on the test number 86.
Norm got 77.61546170% on the test number 86.
Norm got 77.6154617% on the test number 86.
Norm got 77.615462% on the test number 86.
Norm got 77.61546% on the test number 86.
Norm got 77.6155% on the test number 86.
Norm got 77.615% on the test number 86.
Norm got 77.62% on the test number 86.
Norm got 77.6% on the test number 86.
Norm got 78% on the test number 86.
Norm got 78% on the test number 86.
Norm got 77.615462% on the test number 86.


Norm got 77.62% on the test number 86.
Norm got 77.62% on the test number 86.
Norm got 77.615462% on the test number 86.
    Norm got    77.62% on the test number       86.
Norm     got 77.62   % on the test number 86      .


In [39]:
a = 2 * tc.ones((2,1,4))
b = tc.ones((2,2,4))
c = a * b

print(a)
print(b)
print(c)

tensor([[[2., 2., 2., 2.]],

        [[2., 2., 2., 2.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.]]])


In [48]:
print(np.int(2.5))

2
